### ISSUE TITLE
Cyrillic core CCMP test

### ISSUE THREAD

**Issue by EbenSorkin** [Fonthausen/NunitoSans_SSA#9]
One problem found: 

<img width="357" alt="image" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/2181213/97747e98-f420-4e38-8d47-1014d79759b4">

The letter **schwa-cy** has a top anchor but the placement of these anchors is wildly inconsistent. Note too: In the Latin letter **schwa** the anchors are also inconsistent albeit somewhat less wildly so.
🤣

**Comment by Fonthausen** [comment]
@EbenSorkin I can't trace where the issue is coming from. As you can see in the screenshot, the anchor is placed consistently and working. I also checked macroncomb. No errors there either,

<img width="1275" alt="Schermafbeelding 2024-01-09 om 17 40 17" src="https://github.com/Fonthausen/NunitoSans_SSA/assets/20181530/33bca1a7-7d2d-4b39-82ff-628da96df85f">

**Comment by Fonthausen** [comment]
@EbenSorkin I checked the anchors in the latin schwa, schwa-cy and macroncomb. They all looked good.

**Comment by EbenSorkin** [comment]
Great!
